### ISSUE TITLE
小程序无法正常运行呢

### ISSUE THREAD

**Issue by xiaomizhou66** [jas0ncn/szushudong#19]
错误提示：

VM167:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'Promise' of undefined 
 TypeError: Cannot read property 'Promise' of undefined
    at http://127.0.0.1:61136/appservice/npm/wepy-async-function/index.js:14:7
    at require (http://127.0.0.1:61136/appservice/__dev__/WAService.js:22:26841)
    at http://127.0.0.1:61136/appservice/__dev__/WAService.js:22:26448
    at http://127.0.0.1:61136/appservice/app.js:13:1
    at require (http://127.0.0.1:61136/appservice/__dev__/WAService.js:22:26841)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:61136/appservice/appservice?t=1537279701514:1690:23)

**Comment by jas0ncn** [comment]
https://github.com/jas0ncn/szushudong#%E5%BC%80%E5%8F%91%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E
